### ISSUE TITLE
cromite-appimage.sh fails to build on Bazzite Linux

### ISSUE THREAD

**Issue by DIGist** [pkgforge-dev/Cromite-AppImage#10]
cromite-appimage.sh fails on Bazzite (A fedora silverblue variant). Trying to build in a Fedora distrobox.

Attached log:
[cromite appimage sh.txt](https://github.com/user-attachments/files/18238177/cromite.appimage.sh.txt)

**Comment by Samueru-sama** [comment]
Hi, the script is meant to be used in the CI **which uses an Artixlinux container**.  The build script is not meant to run on any distro.

In your case the script is failing because `cp: cannot stat '/usr/lib/libpulse*': No such file or directory` which means you have libpulse directory on a different location in bazzite. 

The AppImage is already built on an Artix container: https://github.com/pkgforge-dev/Cromite-AppImage/actions/runs/12479779714

And you can get it here: https://github.com/pkgforge-dev/Cromite-AppImage/releases

Or fork this repo and run the actions workflow. I'm not a light theme user just in case lol

**Comment by DIGist** [comment]
Thanks for the info, got the working appimage. Any idea why it won't open/parse/load with Gear Lever appimage launcher/manager? 

---- Application startup | version 2.3.2
2024-12-25 00:52:31,389 INFO [AppImageProvider.py:202] Removing /home/user/AppImages/cromite.appimage
2024-12-25 00:52:31,389 INFO [AppImageProvider.py:207] Trashing /home/user/AppImages/cromite.appimage
2024-12-25 00:52:31,394 INFO [AppImageProvider.py:215] Removing /home/user/.local/share/applications/cromite.desktop
2024-12-25 00:52:31,396 WARNING [AppDetails.py:360] Missing app key from app config
2024-12-25 00:55:46,019 INFO [AppImageProvider.py:675] Exctracting with p7zip to /tmp/it.mijorus.gearlever/appimages/gearlever_a2c3ycd134/squashfs-root
2024-12-25 00:56:41,363 INFO [AppImageProvider.py:675] Exctracting with p7zip to /tmp/it.mijorus.gearlever/appimages/gearlever_2x4a25y4yx/squashfs-root
2024-12-25 01:00:16,335 INFO [main.py:63]

**Comment by Samueru-sama** [comment]
> Thanks for the info, got the working appimage. Any idea why it won't open/parse/load with Gear Lever appimage launcher/manager?
> 
> ---- Application startup | version 2.3.2 2024-12-25 00:52:31,389 INFO [AppImageProvider.py:202] Removing /home/user/AppImages/cromite.appimage 2024-12-25 00:52:31,389 INFO [AppImageProvider.py:207] Trashing /home/user/AppImages/cromite.appimage 2024-12-25 00:52:31,394 INFO [AppImageProvider.py:215] Removing /home/user/.local/share/applications/cromite.desktop 2024-12-25 00:52:31,396 WARNING [AppDetails.py:360] Missing app key from app config 2024-12-25 00:55:46,019 INFO [AppImageProvider.py:675] Exctracting with p7zip to /tmp/it.mijorus.gearlever/appimages/gearlever_a2c3ycd134/squashfs-root 2024-12-25 00:56:41,363 INFO [AppImageProvider.py:675] Exctracting with p7zip to /tmp/it.mijorus.gearlever/appimages/gearlever_2x4a25y4yx/squashfs-root 2024-12-25 01:00:16,335 INFO [main.py:63]

Not sure, but I have a feeling that the problem is because Gearlever uses `p7zip` to extract the icon and `.desktop` from the appimage and maybe p7zip doesn't work with DwarFS. 

This AppImage uses this [runtime](https://github.com/VHSgunzo/uruntime) and not the typical [type2-runtime](https://github.com/AppImage/type2-runtime).

The uruntime is fully compatible with the type2-runtime and even delta updates with `appimageupdatetool` work: 

![image](https://github.com/user-attachments/assets/779f170f-ba27-4f9f-9fc2-dd15969bfd66)

If you wonder why I use this runtime, it is because it makes the appimage smaller **and** also faster to launch, using the type2-runtime would make the appimage bigger and add a 1 second delay when launching the app.

So I would raise this issue to Gearlever if I were you, since I make several appimages with this runtime.

Alternative note that Cromite is on AM repo and it is very easy to install and manage: https://github.com/ivan-hc/AM

![image](https://github.com/user-attachments/assets/03a57f60-6a1e-45e3-938b-be179ae57678)

We also use [appimageupdate](https://github.com/AppImageCommunity/AppImageUpdate) to update them while iirc with Gearlever you have to manually give it the url for it to update it.
